// ПРОСТАЯ КОНФИГУРАЦИЯ КНОПОК - ТОЛЬКО ССЫЛКИ
export const topPanelButtons = [
  [
    { name: "ВИДЕОСТОК", url: "https://example.com/videostock", description: "Управление видео контентом" },
    { name: "БИРЖИ / РЫНКИ", url: "https://example.com/markets", description: "Торговые площадки и биржи" },
    { name: "МАГАЗИН", url: "https://example.com/shop", description: "Интернет-магазин товаров" },
    { name: "AI ADS", url: "https://example.com/ai-ads", description: "AI генерация рекламы" },
    { name: "AI АСИСТЕНТЫ", url: "https://example.com/ai-assistants", description: "Виртуальные AI помощники" },
    { name: "AI ГЕНЕРАТОРЫ", url: "https://example.com/ai-generators", description: "AI генерация контента" },
    { name: "ВИДЕОХОСТИНГ", url: "https://example.com/video-hosting", description: "Хостинг видео файлов" },
    { name: "ПОИСК", url: "https://example.com/search", description: "Поиск по системе" },
  ],
  [
    { name: "ФАЙЛЫ/ФУТАЖИ", url: "https://example.com/files", description: "Файловый менеджер" },
    { name: "СЧЕТ/ДЕПОЗИТ", url: "https://example.com/account", description: "Управление счетом" },
    { name: "ТОВАРЫ", url: "https://example.com/products", description: "Каталог товаров" },
    { name: "SMM/MARKETING", url: "https://example.com/smm", description: "Социальный маркетинг" },
    { name: "НВН АСИСТЕНТ", url: "https://example.com/nvn-assistant", description: "Персональный ассистент" },
    { name: "ФОТОГЕНЕРИН", url: "https://example.com/photo-generator", description: "Генерация изображений" },
    { name: "КАНАЛЫ - А", url: "https://example.com/channels-a", description: "Каналы категории А" },
    { name: "СЕРТИФИКАЦИЯ", url: "https://example.com/certification", description: "Сертификаты и лицензии" },
  ],
  [
    { name: "СЕКВЕСОРЫ", url: "https://example.com/sequencers", description: "Управление последовательностями" },
    { name: "СЧЕТ / ESCROW", url: "https://example.com/escrow", description: "Эскроу сервис" },
    { name: "УСЛУГИ", url: "https://example.com/services", description: "Каталог услуг" },
    { name: "НАСТРОЙКИ", url: "https://example.com/settings", description: "Настройки системы" },
    { name: "КОММУНИКАТОР", url: "https://example.com/communicator", description: "Система связи" },
    { name: "АУДИОГЕНЕРИН", url: "https://example.com/audio-generator", description: "Генерация аудио" },
    { name: "КАНАЛЫ - Б", url: "https://example.com/channels-b", description: "Каналы категории Б" },
    { name: "ЦФА / ПАТЕНТ", url: "https://example.com/patents", description: "Цифровые активы и патенты" },
  ],
  [
    { name: "ЭФФЕКТЫ", url: "https://example.com/effects", description: "Визуальные эффекты" },
    { name: "СЧЕТ / WALLET", url: "https://example.com/wallet", description: "Криптовалютный кошелек" },
    { name: "ССЫЛКИ", url: "https://example.com/links", description: "Управление ссылками" },
    { name: "РАСПРЕДЕЛИТЬ", url: "https://example.com/distribute", description: "Система распределения" },
    { name: "CRM / BITRIX", url: "https://example.com/crm", description: "CRM система" },
    { name: "ВИДЕОГЕНЕРИН", url: "https://example.com/video-generator", description: "Генерация видео" },
    { name: "КАНАЛЫ - В", url: "https://example.com/channels-c", description: "Каналы категории В" },
    { name: "ИСПОЛН. ЛИСТ", url: "https://example.com/execution", description: "Исполнительные документы" },
  ],
]

export const bottomPanelSections = [
  {
    id: 1,
    options: [
      "Опция 1",
      "Опция 2",
      "Опция 3",
      "Опция 4",
      "Опция 5",
      "Опция 6",
      "Опция 7",
      "Опция 8",
      "Опция 9",
      "Опция 10",
    ],
    currentIndex: 0,
  },
  {
    id: 2,
    options: [
      "Вариант 1",
      "Вариант 2",
      "Вариант 3",
      "Вариант 4",
      "Вариант 5",
      "Вариант 6",
      "Вариант 7",
      "Вариант 8",
      "Вариант 9",
      "Вариант 10",
    ],
    currentIndex: 0,
  },
  {
    id: 3,
    options: [
      "Режим 1",
      "Режим 2",
      "Режим 3",
      "Режим 4",
      "Режим 5",
      "Режим 6",
      "Режим 7",
      "Режим 8",
      "Режим 9",
      "Режим 10",
    ],
    currentIndex: 0,
  },
  {
    id: 4,
    options: [
      "Настройка 1",
      "Настройка 2",
      "Настройка 3",
      "Настройка 4",
      "Настройка 5",
      "Настройка 6",
      "Настройка 7",
      "Настройка 8",
      "Настройка 9",
      "Настройка 10",
    ],
    currentIndex: 0,
  },
  {
    id: 5,
    options: [
      "Уровень 1",
      "Уровень 2",
      "Уровень 3",
      "Уровень 4",
      "Уровень 5",
      "Уровень 6",
      "Уровень 7",
      "Уровень 8",
      "Уровень 9",
      "Уровень 10",
    ],
    currentIndex: 0,
  },
  {
    id: 6,
    options: [
      "Состояние 1",
      "Состояние 2",
      "Состояние 3",
      "Состояние 4",
      "Состояние 5",
      "Состояние 6",
      "Состояние 7",
      "Состояние 8",
      "Состояние 9",
      "Состояние 10",
    ],
    currentIndex: 0,
  },
  {
    id: 7,
    options: ["Фаза 1", "Фаза 2", "Фаза 3", "Фаза 4", "Фаза 5", "Фаза 6", "Фаза 7", "Фаза 8", "Фаза 9", "Фаза 10"],
    currentIndex: 0,
  },
  {
    id: 8,
    options: ["Блок 1", "Блок 2", "Блок 3", "Блок 4", "Блок 5", "Блок 6", "Блок 7", "Блок 8", "Блок 9", "Блок 10"],
    currentIndex: 0,
  },
  {
    id: 9,
    options: [
      "Секция 1",
      "Секция 2",
      "Секция 3",
      "Секция 4",
      "Секция 5",
      "Секция 6",
      "Секция 7",
      "Секция 8",
      "Секция 9",
      "Секция 10",
    ],
    currentIndex: 0,
  },
  {
    id: 10,
    options: [
      "Канал 1",
      "Канал 2",
      "Канал 3",
      "Канал 4",
      "Канал 5",
      "Канал 6",
      "Канал 7",
      "Канал 8",
      "Канал 9",
      "Канал 10",
    ],
    currentIndex: 0,
  },
]
